config/routes.rb
Rails.application.routes.draw do
  resources :locations do 
    collection do 
      get :maps
     
   
    end
 
  end
   devise_scope :user do
   root 'devise/sessions#new'  
  end
  post '/markers' => 'locations#new_marker'
  get '/markers' => 'locations#markers'

  devise_for :users
  resources :hp_searches

end

app/models/hp_search.rb
class HpSearch < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
end

app/models/marker.rb
class Marker < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
def after_sign_in_path_for(resource) 
locations_path
end
end

app/controllers/hp_searches_controller.rb
class HpSearchesController < ApplicationController
  before_action :set_hp_search, only: [:show, :edit, :update, :destroy]

  # GET /hp_searches
  # GET /hp_searches.json
  def index
    @hp_searches = HpSearch.all
  end

  # GET /hp_searches/1
  # GET /hp_searches/1.json
  def show
  end

  # GET /hp_searches/new
  def new
    @hp_search = HpSearch.new
  end

  # GET /hp_searches/1/edit
  def edit
  end

  # POST /hp_searches
  # POST /hp_searches.json
  def create
    @hp_search = HpSearch.new(hp_search_params)

    respond_to do |format|
      if @hp_search.save
        format.html { redirect_to @hp_search, notice: 'Hp search was successfully created.' }
        format.json { render :show, status: :created, location: @hp_search }
      else
        format.html { render :new }
        format.json { render json: @hp_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hp_searches/1
  # PATCH/PUT /hp_searches/1.json
  def update
    respond_to do |format|
      if @hp_search.update(hp_search_params)
        format.html { redirect_to @hp_search, notice: 'Hp search was successfully updated.' }
        format.json { render :show, status: :ok, location: @hp_search }
      else
        format.html { render :edit }
        format.json { render json: @hp_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hp_searches/1
  # DELETE /hp_searches/1.json
  def destroy
    @hp_search.destroy
    respond_to do |format|
      format.html { redirect_to hp_searches_url, notice: 'Hp search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hp_search
      @hp_search = HpSearch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hp_search_params
      params.require(:hp_search).permit(:name, :zipcode)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.all
    end
  end

  # GET /locations
  # GET /locations.json
 def maps 
  @locations = Location.all
 end

  def markers
    @markers = Marker.all
  end

  def new_marker
    Marker.create(long: params[:d], lat: params[:k])
    redirect_to :back
  end
  # GET /locations/1
  # GET /locations/1.json
  def show
    @markers = Marker.all
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hp_searches_helper.rb
module HpSearchesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/hp_searches/_form.html.erb
<%= form_for(@hp_search) do |f| %>
  <% if @hp_search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hp_search.errors.count, "error") %> prohibited this hp_search from being saved:</h2>

      <ul>
      <% @hp_search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.number_field :zipcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<!-- this whole model/scaffold isnt really doing anything other than acting as and unneeded homepage -->

app/views/hp_searches/edit.html.erb
<h1>Editing Hp Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @hp_search %> |
<%= link_to 'Back', hp_searches_path %>

app/views/hp_searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to 'app name here'!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Zipcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hp_searches.each do |hp_search| %>
      <tr>
        <td><%= hp_search.name %></td>
        <td><%= hp_search.zipcode %></td>
        <td><%= link_to 'Show', hp_search %></td>
        <td><%= link_to 'Edit', edit_hp_search_path(hp_search) %></td>
        <td><%= link_to 'Destroy', hp_search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hp search', new_hp_search_path %>

app/views/hp_searches/new.html.erb
<h1>New Hp Search</h1>

<%= render 'form' %>

<%= link_to 'Back', hp_searches_path %>

app/views/hp_searches/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @hp_search.name %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @hp_search.zipcode %>
</p>

<%= link_to 'Edit', edit_hp_search_path(@hp_search) %> |
<%= link_to 'Back', hp_searches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalapp</title>  <!-- LEAVE THE TURBOLINKS OFF!!!!!!!!!!!! -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <style type="text/css">
      html, body, #map-canvas { height: 97%; margin: 0 auto; padding: 4px;}
    </style>


    <script type="text/javascript"
      src="//maps.googleapis.com/maps/api/js?key=">  <!-- have deleted the API KEY off my github REPO due to security concerens ->
    </script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>



<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="addressbar">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <!-- div class="field">
    <%= f.label :latitude %><br>
    ⃠<%= f.text_field :latitude, :readonly => true %>⃠
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    ⃠<%= f.text_field :longitude, :readonly => true %>⃠
  </div-->
  <div class="actions">
    <%= f.submit %>
  </div>


<p id="addressexpla"> Bring up any location in the world by entering the address or; country, zipcode, city, state, county.  My technology can guess/understand almost any address!  To view your current location, submit any location in the field above and click the <span style="color:red">Find my location</span> button under the map on the next page! </p>

<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Location', new_location_path, class: "large-btn" %>
<h1 id="RSL">Recently Searched Locations</h1>

<!--
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>
 -->

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure you want to delete this location?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

     
  <!-- this button (on this page) doesn't do anything right now, but I want it accessable from most pages -->
<!-- <h1>
 <button id="maptrigger">Find My Location! </button> 
</h1>
 un used maptrigger-->

app/views/locations/maps.html.erb
<!-- was told this was not being utilized -->
<!-- <div id="map-canvas"></div>
   <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: { lat:<%=@locations.first.latitude  %>, lng: <%= @locations.first.longitude %>},
          zoom: 8
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
      }
      google.maps.event.addDomListener(window, 'load', initialize);

    </script>   

  -->

<!-- page not being used delete later! -->

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>
 <!--I keep breaking it get help-->
<!-- <p id="centertagger">o</p> trying to float image on top of map -->


<!-- <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>     TOOK THIS OUT IT IS THE GECODER MAP UNCOMMET TO USE AS A DEVELOPER TOOL -->

<div id="map-canvas"></div>
<%= javascript_tag do %>
  console.log('page initialize');

  window.mapOptions = {
    center: { 
      lat:<%=@location.latitude  %>, 
      lng: <%= @location.longitude %>},
    zoom: 8
  };

  window.markers = [];
  <% @markers.each do |marker| %>
    window.markers.push([<%= marker.lat %>, <%= marker.long %>])
  <% end %>
<% end %>

</div>
<h1>  
  
</h1>

<h2>
 <button id="maptrigger">Find My Location! </button>  <button id="startrigger">I See a meter-maid! </button>  
</h2>
<% nearbys = @location.nearbys(10) %>
<% if nearbys %> 
  <h3>Nearby locations</h3>
  <ul>
  <% nearbys.each do |location| %>
    <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
  <% end %>

  </ul>
 <% end %>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>